[package]
name = "ac_uniswap_contract"
authors = [""]
compiler_version = "0.1"
type = "contract"

[dependencies]
aztec = { path = "../../../../noir-libs/noir-aztec" }
safe_math = { path = "../../../../noir-libs/safe-math" }