name: Push to docs-mirror-test branch

on:
  push:
    branches:
      - ad/fix/mirror-runner
    #paths:
    #  - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.AZTEC_BOT_GITHUB_TOKEN }}

      - name: Push to branch
        run: |
          # constants for easy changes
          CACHE_BRANCH=aztec-bot/docs-git-subrepo-cache
          PREVIOUS_CACHE_BRANCH=origin/$CACHE_BRANCH
          SUBREPO=docs
          SUBREPO_PATH=docs
          # identify ourselves, needed to commit
          git config --global user.email "tech@aztecprotocol.com"
          git config --global user.name "AztecBot"
          # start the next cache branch
          git checkout -b $CACHE_BRANCH
          # if previous cache exists, and we have a newer .gitrepo file there
          # than in our branch, selectively check it out
          if git rev-parse --verify --quiet $PREVIOUS_CACHE_BRANCH ; then
            # Get the subrepo file timestamps
            timestamp_current=$(git log -1 --format="%ct" $CACHE_BRANCH -- "$SUBREPO_PATH"/.gitrepo)
            timestamp_cached=$(git log -1 --format="%ct" $PREVIOUS_CACHE_BRANCH -- "$SUBREPO_PATH"/.gitrepo)
            if [ "$timestamp_cached" -gt "$timestamp_current" ]
            then
              git checkout $PREVIOUS_CACHE_BRANCH $SUBREPO_PATH/.gitrepo
              git commit -am "fetch previous $SUBREPO_PATH/.gitrepo" || true
            fi
          fi
          # push to subrepo, commit locally
          ./scripts/git_subrepo.sh push $SUBREPO_PATH --branch=main
          # push new commit to the history branch, overwrite during conflicts
          git push origin $CACHE_BRANCH --force
